
var data = {
	"5f042ed11c5a070012ac942b": [
		{"value": "Home","icon": "mdi mdi-home"},
		{"value": "Register New Part Master","icon": "mdi mdi-book-variant"},
		{"value": "Katalog Part Master","icon": "mdi mdi-book-variant"}
	],

    "5f042ed11c5a070012ac9430": [
		{"id": "1","value": " Silahkan dipilih"},
		{"id": "2","value": " One"},
		{"id": "3","value": " Two"},
		{"id": "4","value": " Three"}
	],

    "5f042ed11c5a070012ac9430kategori": [
        {"id": "1","value": " Silahkan dipilih"},
		{"id": "2","value": " C"},
		{"id": "3","value": " R"},
		{"id": "4","value": " CN"},
		{"id": "5","value": " T"},
		{"id": "6","value": " J"},
		{"id": "7","value": " SG"},
		{"id": "8","value": " OS"},
		{"id": "9","value": " UF"},
		{"id": "10","value": " D"},
		{"id": "11","value": " HC"},
		{"id": "12","value": " HW"},
		{"id": "13","value": " B"},
		{"id": "14","value": " M"},
		{"id": "15","value": " TE"},
		{"id": "16","value": " W"},
		{"id": "17","value": " PS"},
		{"id": "18","value": " COM"}
	],

	"5f042ed11c5a070012ac9430vendortype": [
		{"id": "1","value": " Silahkan dipilih"},
		{"id": "2","value": " Lokal"},
		{"id": "3","value": " Import"}
	],
    
    "5f042ed11c5a070012ac9430jeniskode": [
		{"id": "1","value": " Silahkan dipilih"},
		{"id": "2","value": " Reguler"},
		{"id": "3","value": " Trial"},
		{"id": "4","value": " Service"}
	],

	"5f042ed11c5a070012ac942e": [
		{
			"id": 1,
			"request date": "17-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "FIBER OPTIC UNIT",
			"size": "E32-D12F 2M",
			"color": "Black",
			"brand": "None",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 2,
			"request date": "18-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "CHUCK ASSY FOR KOMATSU PIN MILLER MACHINE GPM-150F",
			"size": "TYPE : 9K0HZ10013, MAKER : KOMATSU",
			"color": "Black",
			"brand": "None",
			"type": "None",
			"uom consumption":"Unit",
			"category":"R",
			"vendor type":"Import",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 3,
			"request date": "23-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "LM RAIL",
			"size": "SHS20-940L",
			"color": "Silver",
			"brand": "THK",
			"type": "None",
			"uom consumption":"Batang",
			"category":"R",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 4,
			"request date": "25-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "LM BLOCK",
			"size": "SHS20C1SS",
			"color": "Silver",
			"brand": "THK",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 5,
			"request date": "30-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "MOTOR MAGAZINE 14 S2D",
			"size": "6B1105001",
			"color": "Black",
			"brand": "BROTHER",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 6,
			"request date": "01-08-2020",
			"part number": "",
			"draft no": "",
			"part name": "CYCLO TRANSMISSION S2D",
			"size": "6B1104001",
			"color": "Silver",
			"brand": "BROTHER",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 7,
			"request date": "03-08-2020",
			"part number": "",
			"draft no": "",
			"part name": "UNICLEAN",
			"size": "TYPE:151 (25 KG/SAK)",
			"color": "None",
			"brand": "ATOTECH",
			"type": "None",
			"uom consumption":"Sak",
			"category":"C",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 8,
			"request date": "05-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "UNICLEAN",
			"size": "TYPE:157 (25 KG/SAK)",
			"color": "None",
			"brand": "ATOTECH",
			"type": "None",
			"uom consumption":"Sak",
			"category":"C",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 9,
			"request date": "10-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-300",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 10,
			"request date": "17-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-150",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 11,
			"request date": "15-07-2020",
			"part number": "",
			"draft no": "",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-075",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		},
		{
			"id": 12,
			"request date": "05-08-2020",
			"part number": "",
			"draft no": "",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-032",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"Belum ada kode",
			"detail":"Detail"
		}
	],
    
    "5f042ed11c5a070012ac942ekatalog": [
		{
			"id": 1,
			"part number": "RSE-04642-005",
			"draft no": 43920,
			"part name": "FIBER OPTIC UNIT",
			"size": "E32-D12F 2M",
			"color": "Black",
			"brand": "None",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 2,
			"part number": "RSM-12376-001",
			"draft no": 43899,
			"part name": "CHUCK ASSY FOR KOMATSU PIN MILLER MACHINE GPM-150F",
			"size": "TYPE : 9K0HZ10013, MAKER : KOMATSU",
			"color": "Black",
			"brand": "None",
			"type": "None",
			"uom consumption":"Unit",
			"category":"R",
			"vendor type":"Import",
			"status":"ACTIVE"
		},
		{
			"id": 3,
			"part number": "RSM-05915-002",
			"draft no": 43892,
			"part name": "LM RAIL",
			"size": "SHS20-940L",
			"color": "Silver",
			"brand": "THK",
			"type": "None",
			"uom consumption":"Batang",
			"category":"R",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 4,
			"part number": "RSM-12330-001",
			"draft no": 43892,
			"part name": "LM BLOCK",
			"size": "SHS20C1SS",
			"color": "Silver",
			"brand": "THK",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 5,
			"part number": "RSE-05328-001",
			"draft no": "43873",
			"part name": "MOTOR MAGAZINE 14 S2D",
			"size": "6B1105001",
			"color": "Black",
			"brand": "BROTHER",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 6,
			"part number": "RSM-12257-001",
			"draft no": "43871",
			"part name": "CYCLO TRANSMISSION S2D",
			"size": "6B1104001",
			"color": "Silver",
			"brand": "BROTHER",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"R",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 7,
			"part number": "CPW-00114-002",
			"draft no": "44871",
			"part name": "UNICLEAN",
			"size": "TYPE:151 (25 KG/SAK)",
			"color": "None",
			"brand": "ATOTECH",
			"type": "None",
			"uom consumption":"Sak",
			"category":"C",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 8,
			"part number": "CPW-00114-001",
			"draft no": "44872",
			"part name": "UNICLEAN",
			"size": "TYPE:157 (25 KG/SAK)",
			"color": "None",
			"brand": "ATOTECH",
			"type": "None",
			"uom consumption":"Sak",
			"category":"C",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 9,
			"part number": "TLG-01966-010",
			"draft no": "45870",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-300",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 10,
			"part number": "TLG-01966-009",
			"draft no": "45871",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-150",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 11,
			"part number": "TLG-01966-008",
			"draft no": "45872",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-075",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"ACTIVE"
		},
		{
			"id": 12,
			"part number": "TLG-01966-007",
			"draft no": "45873",
			"part name": "TNE HANDTOOL",
			"size": "EXTENSION BAR EX31-032",
			"color": "None",
			"brand": "TONE",
			"type": "None",
			"uom consumption":"Pcs",
			"category":"T",
			"vendor type":"Local",
			"status":"ACTIVE"
		}
    ],
    
	"5f0437411c5a070012ac96fe": []
};
webix.proxy.demo = {
	$proxy:true,
	load:function(view){
		if (view.count && view.count())
			view.clearAll();
		view.parse( webix.copy(data[this.source]||[]) );
	}
};
